### ISSUE TITLE
Add virtual camera support

### ISSUE THREAD

**Issue by Certurix** [mmbaguette/Roblox-VR-with-Webcam#1]
### Issue Type
New feature/Enhancement

### Description
A lot of people (like me) don't have a real physical camera, but use instead their phone or tablet to get a webcam. 
So, it would be very nice to have this new feature implemented.
The idea is to have a dropdown of all cameras the computer have (like you would have in Discord for example) and select which one we can use.

### Tasks

- [ ] Add support for virtual cameras

- [ ] Add a dropdown menu when no camera is detected to select one

**Comment by mmbaguette** [comment]
Good suggestion, but adding graphics for the drop-down menu you want is much more work for me, as this was just meant to be a terminal application. Maybe someone else can contribute. But for your case you don't need it because the library I'm using that captures the webcam is OpenCV and it should take your default webcam on its own. As for the virtual camera, there'  special applications made for "Using iPhone or Android as webcam": https://www.elgato.com/en/epoccam.

Let me know if that app helps so I can add it to the description. Sorry I couldn't do GUI for this.

**Comment by Certurix** [comment]
I already use Camo Studio as a converter for my phone to use my webcam from it. It's probably the same for epoc cam. 

My virtual webcam is not truly a real webcam for Windows. When I go into the Camera app of Windows, it says no webcam detected, because virtual cameras are not real cameras. Yes it's a bit weird. So I don't think OpenCV will detect theses types of camera, or maybe by editing something, i don't really know.

No worry for the GUI, and instead of using this, why not making a prompt in the terminal app and make a list with every cameras and every key, and when you press that key, it select the camera choosed.

**Comment by mmbaguette** [comment]
EpocCam provides a virtual camera driver like in OBS that you can select in a drop-down menu like in Discord. If it appears there, then it will work for this too.
